AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Vehicle API Demo

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    Handler: vehicle_handler.lambda_handler
    Environment:
      Variables:
        TABLE_NAME: vehicle-demo

Resources:

  VehicleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: vehicle-demo
      AttributeDefinitions:
        - AttributeName: vin
          AttributeType: S
      KeySchema:
        - AttributeName: vin
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  VehicleLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: vehicle-demo
      Events:
        GetVehicles:
          Type: Api
          Properties:
            Path: /vehicles
            Method: GET
        CreateVehicle:
          Type: Api
          Properties:
            Path: /vehicle
            Method: POST
        DeleteVehicle:
          Type: Api
          Properties:
            Path: /vehicle
            Method: DELETE
