AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Vehicle API Demo

Resources:
  VehicleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: vehicle-demo
      AttributeDefinitions:
        - AttributeName: vin
          AttributeType: S
      KeySchema:
        - AttributeName: vin
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  VehicleLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Runtime: python3.13
      Handler: handler.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: vehicle-demo
        - AWSLambdaBasicExecutionRole
      Events:
        GetVehicles:
          Type: Api
          Properties:
            Path: /vehicles
            Method: GET
        CreateVehicle:
          Type: Api
          Properties:
            Path: /vehicle
            Method: POST
        DeleteVehicle:
          Type: Api
          Properties:
            Path: /vehicle
            Method: DELETE

  SummaryLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: summary.lambda_handler
      Runtime: python3.13
      Policies:
        - DynamoDBReadPolicy:
            TableName: vehicle-demo
        - S3WritePolicy:
            BucketName: !Ref SummaryBucket
      Events:
        WeeklyTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(7 days)

  SummaryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "vehicle-summary"